# Generated by Django 6.0.4 on 2026-04-26 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=13)),
                ('lieuNais', models.CharField(max_length=30)),
                ('dateNais', models.DateField()),
                ('Quartier', models.CharField(max_length=50)),
                ('Avenu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomService', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appl.agent')),
                ('Po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appl.poste')),
                ('Se', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appl.service')),
            ],
        ),
    ]
